- name: Install Docker on app and jenkins
  hosts: _app,_jenkins
  become: yes
  roles:
    - role: ansible-role-docker

- name: Install Java 
  hosts: _jenkins
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present


- name: Install jenkins on jenkins
  hosts: _jenkins
  become: yes
  roles:
    - role: ansible-role-jenkins
