- name: Install Docker on app and jenkins
  hosts: app,jenkins
  become: yes
  roles:
    - role: ansible-role-docker

- name: Install jenkins on jenkins
  hosts: jenkins
  become: yes
  roles:
    - role: ansible-role-jenkins
